### ISSUE TITLE
右侧文章目录显示不全

### ISSUE THREAD

**Issue by AloneAlive** [SukkaW/hexo-theme-suka#134]
很喜欢这个主题，速度很快界面简洁，想用这个主题。
但是有个小小的问题，目录太多，右侧会显示不全。
我在作者最新的文章也看到了这个现象。
请问怎么解决这个问题？

感谢！

**Comment by AloneAlive** [comment]
修改方式：
在style.min.css中修改：
```css
#post-toc>ol{margin-left:2rem;max-width:12rem;position:fixed;z-index:0;top:13.5rem;display:inline-block;text-align:left;height:60%;overflow-y:auto;}
```
另外style.css中修改好像not work.
