### ISSUE TITLE
local search功能无法使用，报错Cannot GET /search/

### ISSUE THREAD

**Issue by Holton1** [SukkaW/hexo-theme-suka#138]
**I certify that I have first consulted** (check with "x")

**我确认我已经查看了** (选择时请使用 "x" 取代方括号中的空格)

- [ x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [ x] [Suka Theme documentation | Suka Theme 文档](https://theme-suka.skk.moe/docs/)
- [ x] [Suka theme issues | Suka 主题的其它 issue](https://github.com/SukkaW/hexo-theme-suka/issues?utf8=%E2%9C%93&q=is%3Aissue)

我在站点_config.yml中添加了：
suka_theme:
  search:
    enable: true
    path: search.xml
    field: post # Page | Post | All. Default post
  prism:
    enable: true
    line_number: true
    theme: default
并做了hexo clean, hexo g
但是search功能不能使用。在网页点击search，会报错Cannot GET /search/

**Comment by Rhysn** [comment]
试着修改主题配置文件
```
search:
    use: true
    link: /search.html
  pages:
    About:
      link: /about.html
    #Friends:
      #link: /links/
```

或者将search.html修改成 `/search/index.html`
