### ISSUE TITLE
我该如何处理_config.yml文件中的敏感信息，比如valine id&key

### ISSUE THREAD

**Issue by Mesimpler** [SukkaW/hexo-theme-suka#152]
我将整个hexo项目部署到了仓库的master分支
使用hexo deploy将静态文件部署到同一仓库的gh-pages分支。

我该如何处理_config.yml文件中的敏感信息
```yml
valine:
    leancloud_appId: process.env.VALINEID
    leancloud_appKey: ${SYSTEMVAL_VALINEKEY}
```
yml配置文件仿佛是静态文件，无法在编译时从虚拟机线程或系统环境变量中拿到这些值
