### ISSUE TITLE
无法启用search/无法建立独立页面

### ISSUE THREAD

**Issue by little1CE** [SukkaW/hexo-theme-suka#20]
I certify that I have first consulted (check with "x")

我确认我已经查看了 (选择时请使用 "x" 取代方括号中的空格)

  - [x] Hexo documentation | Hexo 文档
  - [x] Suka Theme documentation | Suka Theme 文档
  - [x] Suka theme issues | Suka 主题的其它 issue
--------------
I'm submitting a (check one with "x")
我正在申请 (选择时请使用 "x" 取代方括号中的空格)
  - [x] bug report | 反馈一个 Bug
  - [ ] feature request | 申请添加新的特性或功能
  - [x] support request | 请求技术支持
----------------
# 无法启用search页面
完全按照 https://theme.suka.moe/docs//plugin/index.html 进行了设置
主题配置文件中
```
...
search:
  use: local
  # Swiftype
  swiftype_key:
...
nav:
  home:
    use: true
  archives:
    use: true
  rss:
    use: false
  share:
    use: true
  search:
    use: true
    link: /search
  ...
```
站点配置文件中
```
...
suka_theme:
  search:
    path: search.json
    field: post # Page | Post | All. Default post
  prism:
    line_number: true
    theme: default
...
```
当我点击search时 提示 ```Cannot GET /search```

# 无法建立独立页面
按照文档一样建立friends页面和tags页面均失败（提示都是 can't get /links/tags），不知道是否我理解错误，可否在文档中建立独立页面写的再详细一点？当我想要建立一个独立about页后，在主题配置文件中nav中开启了about页面，我应该如何填写和选择文件路径？about.md文件应该放到根目录的source下还是sources/about下？（实在是小白orz

-------------
## package.json
```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.7.1"
  },
  "dependencies": {
    "gitalk": "^1.4.0",
    "hexo": "^3.7.0",
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-search": "^2.2.5",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-marked": "^0.3.2",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.1",
    "hexo-tag-aplayer": "^3.0.4"
  }
}
```
-----
我目前正在搭建的使用该模板的博客
http://little1ce.github.io

**Comment by SukkaW** [comment]
站点配置文件在 1.1.0 版本有升级，请修改站点配置文件中 `suka_theme` 部分为

```yaml
suka_theme:
  search:
    enable: true
    path: search.json
    field: post # Page | Post | All. Default post
  prism:
    enable: true
    line_number: true
    theme: default
```
