### ISSUE TITLE
文章页面显示的目录不全

### ISSUE THREAD

**Issue by GreenHatHG** [SukkaW/hexo-theme-suka#98]
**我确认我已经查看了(选择时请使用 "x" 取代方括号中的空格)**

- [x ] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)

- [x ] [Suka Theme documentation | Suka Theme 文档](https://theme-suka.skk.moe/docs/)
- [x ] [Suka theme issues | Suka 主题的其它 issue](https://github.com/SukkaW/hexo-theme-suka/issues?utf8=%E2%9C%93&q=is%3Aissue)

------

```
npm -v : 6.10.1
node -v : v11.7.0
```

------

### package.json

站点目录

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.9.0"
  },
  "dependencies": {
    "braces": "^3.0.2",
    "eslint": "^6.0.1",
    "hexo": "^3.9.0",
    "hexo-asset-image": "^1.0.0",
    "hexo-deployer-git": "^1.0.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-kramed": "^0.1.4",
    "hexo-renderer-mathjax": "^0.6.0",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.1",
    "lodash": "^4.17.14"
  }
}
```

主题目录

```
{
  "name": "hexo-theme-suka",
  "version": "1.3.3",
  "description": "Modern, powerful and simple theme for Hexo",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "setup": "npm cache clean && npm install",
    "lint": "bash lint.sh"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/SukkaW/hexo-theme-suka.git"
  },
  "keywords": [
    "hexo",
    "hexo-theme",
    "suka",
    "sukkaw"
  ],
  "author": "SukkaW",
  "license": "GPL-3.0",
  "bugs": {
    "url": "https://github.com/SukkaW/hexo-theme-suka/issues"
  },
  "homepage": "https://github.com/SukkaW/hexo-theme-suka#readme",
  "devDependencies": {
    "ejs-lint": "0.3.0",
    "eslint": "5.16.0",
    "gulp": "4.0.2",
    "gulp-autoprefixer": "6.1.0",
    "gulp-clean-css": "4.2.0",
    "gulp-rename": "1.4.0",
    "gulp-uglify": "3.0.2",
    "sass-lint": "1.13.1"
  },
  "dependencies": {
    "json-stringify-safe": "5.0.1",
    "node-prismjs": "0.1.2",
    "prismjs": "1.16.0",
    "qr-image": "3.2.0"
  }
}
```

### hexo版本

```
hexo-cli: 2.0.0
os: Linux 5.2.0-arch2-1-ARCH linux x64
node: 11.7.0
v8: 7.0.276.38-node.16
uv: 1.24.1
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 67
nghttp2: 1.34.0
napi: 3
llhttp: 1.0.1
http_parser: 2.8.0
openssl: 1.1.0j
cldr: 34.0
icu: 63.1
tz: 2018e
unicode: 11.0
```

------

已开启toc

```
toc:                                                                                                                                        
  # You can still disable toc for each single post by setting their front-matter with 'toc: false'                                          
  enable: true                                                                                                                              
  # Show line number for each toc list-item or not. Default is true.                                                                        
  line_number: true
```

------

使用的浏览器：Google Chrome  75.0.3770.100（正式版本） （64 位）

使用的系统：Arch Linux x86_64 5.2.0-arch2-1-ARCH

------

# 出现的问题

**文章页面显示的目录不全，已经将滚动条拖到末尾**

![](/home/cc/Pictures/2019-07-12_23-24.png)

文章地址：

[Arch安装配置笔记](https://greenhathg.github.io/2019/02/15/Arch安装配置笔记/)
